#!/usr/bin/env python
# -*- coding; utf8 -*-

"""
Overview
========

A small but useful tool to sniffer memcache query
contact: qingqibai@gmail.com

Usage summary
=============

You need to install python-pypcap and python-dpkt to run this tool
you may:
    apt-get install python-pypcap
    apt-get install python-dpkt
or:
    pip install python-pypcap
    pip install python-dpkt

How to use memcache-sniffer to sniffer query::
    You can get help with ./memcache-sniffer -h or ./mysql-sniffer --help
    ./memcache-sniffer -ieth1 -p11211 -r0.2
    ./memcache-sniffer -ieth1 -f'host 10.4.16.21 and tcp dst port 11211'
    -i or --interface: the interface you want to siniffer
    -p or --port: the memcache port you use
    -f or --filter: filter, defalut None, would use "dst you host and tcp dst port you port 
    -r or --radio: filter radio, from 0 to 1, default 1 means sniffer all query
    -o or --output-file: output file, if set it will print the query to this file instead of stdout, defult None.
"""

import argparse
import pcap
import dpkt
import socket
import fcntl
import struct
from random import random
from datetime import datetime

class MemcacheSniffer(object):

    def __init__(self, interface, port, filter, ratio, output_file):
        self.interface = interface
        self.port = port
        self.filter = filter
        self.ratio = ratio
        self.output_file = output_file

    def get_ip_address(self, ifname):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        return socket.inet_ntoa(fcntl.ioctl(
            s.fileno(),
            0x8915,  # SIOCGIFADDR
            struct.pack('256s', ifname[:15])
        )[20:24])


    def bin2ip(self, binary):
        return ".".join([str(x) for x in map(ord, binary)])

    def print_query(self, ts, src, dst, sport, dport, data):
        data = data.lower()
        commands = ['get', 'set', 'delete']
        is_valid_command = False
        for c in commands:
            if data.startswith(c):
                is_valid_command = True
                break
        if not is_valid_command:
            return
        if random() > self.ratio:
            return
        query = "%s %s:%d %s" % (datetime.fromtimestamp(ts), src, sport, data.strip().replace("\n", ''))
        if self.output_file:
            with open(self.output_file, 'a') as f:
                f.write(query + "\n")
        else:
            print query

    def start_sniffer(self):
        pc = pcap.pcap(name = self.interface)
        if not self.filter:
            self.filter = "dst host %s and tcp dst port %d" % (self.get_ip_address(self.interface), self.port)
        print 'sniffer filter: %s' % self.filter
        pc.setfilter(self.filter)
        decode = { pcap.DLT_LOOP : dpkt.loopback.Loopback,
                   pcap.DLT_NULL : dpkt.loopback.Loopback,
                   pcap.DLT_EN10MB : dpkt.ethernet.Ethernet }[pc.datalink()]
        for ts, raw_pkt in pc:
            ip_pkt = decode(raw_pkt).data
            tcp_pkt = ip_pkt.data
            if tcp_pkt.flags & dpkt.tcp.TH_PUSH:
                if len(tcp_pkt.data) < 6:
                    continue
                self.print_query(ts, self.bin2ip(ip_pkt.src), self.bin2ip(ip_pkt.dst), \
                        tcp_pkt.sport, tcp_pkt.dport, tcp_pkt.data)

def main():
    parser = argparse.ArgumentParser(description="Sniffer memcached.")
    parser.add_argument("-i", "--interface", type=str, nargs="?", help="interface you want to sniffer", default="eth1")
    parser.add_argument("-p", "--port", type=int, nargs="?", help="the memcached port used", default=11211)
    parser.add_argument("-f", "--filter", type=str, nargs="?", help="packet filter", default=None)
    parser.add_argument("-r", "--ratio", type=float, nargs="?", help="filter ratio from 0 to 1", default=1) # 100%
    parser.add_argument("-o", "--output-file", type=str, nargs="?", help="output file", default=None)
    args = parser.parse_args()
    print 'ratio=%f, outfile=%s' % (args.ratio, args.output_file)
    sniffer = MemcacheSniffer(args.interface, args.port, args.filter, args.ratio, args.output_file)
    sniffer.start_sniffer()

if __name__ == "__main__":
    main()
